### ISSUE TITLE
Performance gain?

### ISSUE THREAD

**Issue by bablokb** [graeme-winter/circuitpython-mandelbrot-esp32#1]
I am following the CircuitPython repo and was directed here by your issue about esp32 and native modules. One of the projects on my todo-list is about fractals and I was wondering how much performance gain I can expect with a native module like you created here compared to a pure python implementation?

**Comment by graeme-winter** [comment]
I am certain that this is the case. On ARM (cortex M4, M7) this is pretty performant as a brute force Mandelbrot set calculator - this is a port of my original ARM assembly to C

I am currently trying to get native modules to work on non-ARM platforms (e.g. ESP32) but if you are on ARM it is very easy

**Comment by bablokb** [comment]
Thanks! I think native modules would be a great addon for CircuitPython and support for all platforms would be helpful. For example I have a project using the Pico and I am currently swapping it for a size and pin-compatible ESP32-S3. So your work is highly appreciated.
